run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - hack
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/albertofilice/node-check-operator

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

