const { ConsoleRemotePlugin } = require('@openshift-console/dynamic-plugin-sdk-webpack');
const path = require('path');

module.exports = (env, argv) => {
  const isDevelopment = argv.mode === 'development';
  
  return {
    entry: {}, // Plugin container entry is generated by ConsoleRemotePlugin
    output: {
      path: path.resolve(__dirname, 'dist'),
      clean: true,
    },
    devtool: isDevelopment ? 'eval-source-map' : 'source-map',
    devServer: {
      port: 9001,
      hot: true,
      open: false,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Origin, Content-Type, Accept, Authorization, X-Requested-With',
      },
      // Proxy API requests to mock server or real backend
      proxy: [
        {
          context: ['/api/v1'],
          target: 'http://localhost:3001',
          changeOrigin: true,
          secure: false,
          logLevel: 'debug',
        },
      ],
      // Serve plugin files at the path OpenShift Console expects
      static: [
        {
          directory: path.join(__dirname, 'dist'),
          publicPath: '/api/plugins/node-check-console-plugin/',
        },
        {
          directory: path.join(__dirname),
          publicPath: '/',
        },
      ],
    },
    plugins: [
      new ConsoleRemotePlugin({
        // ConsoleRemotePlugin gestisce automaticamente le dipendenze condivise tramite Module Federation
        // Legge le dipendenze da package.json consolePlugin.dependencies e peerDependencies
        // React e React-DOM sono forniti dalla console host come moduli condivisi (singleton)
        // NON usare externals - ConsoleRemotePlugin configura Module Federation automaticamente
        // e legge le dipendenze condivise da peerDependencies
        validateSharedModules: false,
        validateExtensionIntegrity: false,
      }),
    ],
    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.jsx'],
    },
    module: {
      rules: [
        {
          test: /\.(ts|tsx)$/,
          exclude: /node_modules/,
          use: {
            loader: 'ts-loader',
            options: {
              transpileOnly: true,
              compilerOptions: {
                skipLibCheck: true,
      },
    },
          },
        },
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader'],
        },
      ],
    },
};
};